baseUrl: 'https://nexuspunktech.agency'
enabled: true
handle: nexus_punk_tech
hasUrls: true
language: en
name: Nexuspunktech.agency
primary: true
siteGroup: f0c0f780-e0b4-46ca-866b-ef8f8384b774 # nexuspunktech
sortOrder: 2
